### ISSUE TITLE
Some of the artists name disappear when you play a song, and some of the songs has the wrong artist on display

### ISSUE THREAD

**Issue by sebsebby** [MetrolistGroup/Metrolist#1020]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/mostafaalagamy/Metrolist/actions).
- [x] I've checked that there is no open or closed issue about this bug.
- [x] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

.
### Expected behavior

I should be able to see the artist, and it should be the right artist 

### Actual behavior

When i play a song, or search for it, some of the songs won't show the artist below the title, or it would show a different artist. And when i tap it, it would endlessly load showing only a loading animation.

### Screenshots/Screen recordings

Some of the songs display the wrong artist. Some of them are just letters. Also, there are songs who doesn't show the artist on their albums or when you play them.

<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/de163f0f-b447-43a2-8e50-171afeab9b76" />

### Logs

.

### Metrolist version

Version 12.2.0

### Android version

Android 11

**Comment by lolouthefox** [comment]
I have the same issue. None of the songs synced in the liked playlist have the artist name...

**Comment by ghostteammj** [comment]
If I have the same problem, I hope they find or fix it.

**Comment by kaneryu** [comment]
I have the same issue. For song artists, the root cause is the album not being "associated" with the artist (aka. not on the artists page) which YouTube does often for some reason. If not associated, the artist name gets erased from the library constantly, which is very annoying and disables scrobbling. This also makes it impossible to use albums that have multiple artists in it (like Various Artists albums)

**Comment by SarthakRaymondal** [comment]
Click on the 3 dots and clixk refetch. This should return with the artist name and all other misssng elements of the song.

**Comment by mostafaalagamy** [comment]
I want to test if this fixed the problem or if it's still ongoing!

**Comment by SarthakRaymondal** [comment]
> I want to test if this fixed the problem or if it's still ongoing!

Well this happened to me too and click the refetch brought back the artist name.

**Comment by mostafaalagamy** [comment]
> > I want to test if this fixed the problem or if it's still ongoing!
> 
> Well this happened to me too and click the refetch brought back the artist name.

Yes, you're right—this fixes part of the problem. But on the home screen, artists' names are displayed incorrectly. The previous commit was supposed to have resolved this issue for me!

**Comment by SarthakRaymondal** [comment]
> > > I want to test if this fixed the problem or if it's still ongoing!
> > 
> > 
> > Well this happened to me too and click the refetch brought back the artist name.
> 
> Yes, you're right—this fixes part of the problem. But on the home screen, artists' names are displayed incorrectly. The previous commit was supposed to have resolved this issue for me!

Oh!K i'll also check then

**Comment by kaneryu** [comment]
> Click on the 3 dots and clixk refetch. This should return with the artist name and all other misssng elements of the song.

This is correct, however the issue occurs constantly. It continuously erases the artist name.

**Comment by Monoxide8969** [comment]
Does this still happen to any of you?

**Comment by kaneryu** [comment]
Yes, the newest fix didn't really fix the issue. It just replaces the song artist with the album artist. This works in about 60% of cases, but when a album has multiple artists or different artists on each song, it just overwrites all of the artists with something like "Various Artists". The only true solution is to run refetch on each song, which often works instantly. Please refetch the song data instead of just replacing it with the album aritst.

**Comment by TechnoSparks** [comment]
In my case i notice artist names are missing on auto playlist "Liked".

When browsing the Liked Music playlist at Home screen, the artist names appear normally.

**Comment by nyxiereal** [comment]
fixed now afaik

**Comment by kaneryu** [comment]
It's not fixed on the latest version. The issue still exists as I described

**Comment by TechnoSparks** [comment]
Issue still persist on current version 13.3.0, specifically for me Artist Name is not populated for the song item. 
Affected areas:
- In the list
- on the Now Playing screen
- Auto "Liked" playlist

Workaround: Menu -> Refetch. Impractical as it affects large playlists meaning a lot of songs missing artist name

Proposed solution:
- Metrolist to always refetch if information not filled
- Allow users to bulk fetch metadata
  - Maybe a Fetch All action in playlist submenu

**Comment by kaneryu** [comment]
+1 on adding a fetch all, and In addition, fetch all should be added to multi select as well.
